import type { CardDef } from '../engine/types';

const 攻 = '攻擊', 技 = '技能', 能 = '能力';

export const cards: CardDef[] = [
  // ===== 起手 =====
  { id: 'sanjo', name: '參上', cost: 1, type: 攻, rarity: '常見', pool: '起手', target: 'enemy', art: 'ninja/01',
    effects: [{ kind: 'damage', amount: 6 }], upgrade: { effects: [{ kind: 'damage', amount: 9 }] } },
  { id: 'tanding', name: '淡定', cost: 1, type: 技, rarity: '常見', pool: '起手', target: 'self', art: 'ninja/32',
    effects: [{ kind: 'block', amount: 5 }], upgrade: { effects: [{ kind: 'block', amount: 8 }] } },
  { id: 'kawarimi', name: '忍術·替身術', cost: 0, type: 技, rarity: '常見', pool: '起手', target: 'self', art: 'ninja/08',
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'draw', n: 1 }] } },

  // ===== 忍術（33） =====
  { id: 'shunkan', name: '忍術·瞬間移動', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'ninja/03',
    effects: [{ kind: 'damage', amount: 7, ignoreBlock: true }], upgrade: { effects: [{ kind: 'damage', amount: 10, ignoreBlock: true }] } },
  { id: 'shengdong', name: '忍術·聲東擊西', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'ninja/19',
    effects: [{ kind: 'damage', amount: 5 }, { kind: 'status', name: '懶洋洋', amount: 1, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 7 }, { kind: 'status', name: '懶洋洋', amount: 2, target: 'enemy' }] } },
  { id: 'shunshou', name: '忍術·順手牽羊', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'ninja/20',
    effects: [{ kind: 'damage', amount: 6 }, { kind: 'gold', n: 15, onKill: true }],
    upgrade: { effects: [{ kind: 'damage', amount: 9 }, { kind: 'gold', n: 25, onKill: true }] } },
  { id: 'wozaizhe', name: '我在這', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'ninja/02',
    effects: [{ kind: 'damage', amount: 6 }, { kind: 'drawIfTargetStatus', name: '翻肚', n: 1 }],
    upgrade: { effects: [{ kind: 'damage', amount: 9 }, { kind: 'drawIfTargetStatus', name: '翻肚', n: 1 }] } },
  { id: 'jiaochulai', name: '交出來', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'ninja/27',
    effects: [{ kind: 'stealBlock' }, { kind: 'damage', amount: 4 }], upgrade: { effects: [{ kind: 'stealBlock' }, { kind: 'damage', amount: 6 }] } },
  { id: 'susu', name: '速速退散', cost: 2, type: 攻, rarity: '常見', pool: '忍術', target: 'all', art: 'ninja/28',
    effects: [{ kind: 'damage', amount: 8, target: 'all' }], upgrade: { effects: [{ kind: 'damage', amount: 11, target: 'all' }] } },
  { id: 'bunshin', name: '忍術·分身術', cost: 1, type: 攻, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'ninja/10',
    effects: [{ kind: 'damage', amount: 3, scaleWithCombo: true, comboCap: 5 }],
    upgrade: { effects: [{ kind: 'damage', amount: 4, scaleWithCombo: true, comboCap: 5 }] } },
  { id: 'ruying', name: '如影隨形', cost: 2, type: 攻, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'ninja/26',
    effects: [{ kind: 'damage', amount: 5, times: 2 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'damage', amount: 7, times: 2 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }] } },
  { id: 'zhangyan', name: '忍術·障眼法', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/07',
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'draw', n: 1 }],
    upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'draw', n: 2 }] } },
  { id: 'yinshen', name: '忍術·隱身術', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/09',
    effects: [{ kind: 'status', name: '隱身', amount: 2, target: 'self' }], upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 3, target: 'self' }] } },
  { id: 'bianshen', name: '忍術·變身術', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/11',
    effects: [{ kind: 'block', amount: 9 }], upgrade: { effects: [{ kind: 'block', amount: 12 }] } },
  { id: 'zhuangsi', name: '忍術·裝死術', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/13', keywords: ['消耗'],
    effects: [{ kind: 'block', amount: 5 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'block', amount: 8 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }] } },
  { id: 'duxin', name: '忍術·讀心術', cost: 0, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/15',
    effects: [{ kind: 'scry', n: 3 }, { kind: 'draw', n: 1 }], upgrade: { effects: [{ kind: 'scry', n: 5 }, { kind: 'draw', n: 1 }] } },
  { id: 'qianliyan', name: '千里眼', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/22',
    effects: [{ kind: 'draw', n: 2 }], upgrade: { effects: [{ kind: 'draw', n: 3 }] } },
  { id: 'shunfenger', name: '順風耳', cost: 0, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/23',
    effects: [{ kind: 'drawNextTurn', n: 2 }], upgrade: { effects: [{ kind: 'drawNextTurn', n: 3 }] } },
  { id: 'dingshang', name: '盯上你了', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'enemy', art: 'ninja/30',
    effects: [{ kind: 'status', name: '翻肚', amount: 2, target: 'enemy' }], upgrade: { effects: [{ kind: 'status', name: '翻肚', amount: 3, target: 'enemy' }] } },
  { id: 'chudashi', name: '出大事了', cost: 0, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/33',
    effects: [{ kind: 'draw', n: 2 }, { kind: 'status', name: '翻肚', amount: 1, target: 'self' }], upgrade: { effects: [{ kind: 'draw', n: 2 }] } },
  { id: 'youcike', name: '有刺客', cost: 0, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/29', keywords: ['消耗'],
    effects: [{ kind: 'draw', n: 2 }], upgrade: { effects: [{ kind: 'draw', n: 3 }] } },
  { id: 'zhanshu', name: '戰術撤退', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/37',
    effects: [{ kind: 'block', amount: 8 }, { kind: 'noAttacksThisTurn' }], upgrade: { effects: [{ kind: 'block', amount: 11 }, { kind: 'noAttacksThisTurn' }] } },
  { id: 'tuozi', name: '忍術·拖字訣', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'ninja/24',
    effects: [{ kind: 'retainFromHand', n: 1 }, { kind: 'draw', n: 1 }], upgrade: { effects: [{ kind: 'retainFromHand', n: 2 }, { kind: 'draw', n: 1 }] } },
  { id: 'shuaiguo', name: '忍術·甩鍋術', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'ninja/06',
    effects: [{ kind: 'transferDebuffs' }], upgrade: { cost: 0 } },
  { id: 'dingshen', name: '忍術·定身術', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'ninja/12',
    effects: [{ kind: 'status', name: '定身', amount: 1, target: 'enemy' }], upgrade: { cost: 0 } },
  { id: 'cuimian', name: '忍術·催眠術', cost: 2, type: 技, rarity: '罕見', pool: '忍術', target: 'all', art: 'ninja/14',
    effects: [{ kind: 'status', name: '懶洋洋', amount: 2, target: 'all' }, { kind: 'status', name: '炸毛', amount: 2, target: 'all' }],
    upgrade: { effects: [{ kind: 'status', name: '懶洋洋', amount: 3, target: 'all' }, { kind: 'status', name: '炸毛', amount: 3, target: 'all' }] } },
  { id: 'fengkou', name: '忍術·封口術', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'ninja/05',
    effects: [{ kind: 'removeStatuses', names: ['爪力', '貓步'], removeBlock: true }],
    upgrade: { effects: [{ kind: 'removeStatuses', names: ['爪力', '貓步'], removeBlock: true }, { kind: 'status', name: '翻肚', amount: 1, target: 'enemy' }] } },
  { id: 'qianshui', name: '忍術·潛水術', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'ninja/25',
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'status', name: '潛水', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 2, target: 'self' }, { kind: 'status', name: '潛水', amount: 2, target: 'self' }] } },
  { id: 'touchi', name: '忍術·偷吃術', cost: 0, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'ninja/21', keywords: ['消耗'],
    effects: [{ kind: 'energy', n: 1 }], upgrade: { effects: [{ kind: 'energy', n: 1 }, { kind: 'draw', n: 1 }] } },
  { id: 'xianshuile', name: '先睡了', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'ninja/38',
    effects: [{ kind: 'heal', n: 4 }, { kind: 'endTurn' }], upgrade: { effects: [{ kind: 'heal', n: 7 }, { kind: 'endTurn' }] } },
  { id: 'gaotui', name: '告退', cost: 0, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'ninja/39', keywords: ['消耗'],
    effects: [{ kind: 'exhaustFromHand', n: 1 }, { kind: 'draw', n: 1 }], upgrade: { effects: [{ kind: 'exhaustFromHand', n: 1 }, { kind: 'draw', n: 2 }] } },
  { id: 'meikandao', name: '我什麼都沒看到', cost: 2, type: 技, rarity: '稀有', pool: '忍術', target: 'self', art: 'ninja/31', keywords: ['消耗'],
    effects: [{ kind: 'immuneThisTurn' }], upgrade: { cost: 1 } },
  { id: 'jiejie', name: '結界', cost: 2, type: 能, rarity: '罕見', pool: '忍術', target: 'self', art: 'ninja/17',
    effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'block', amount: 3 }] }],
    upgrade: { effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'block', amount: 4 }] }] } },
  { id: 'fantan', name: '反彈', cost: 1, type: 能, rarity: '罕見', pool: '忍術', target: 'self', art: 'ninja/16',
    effects: [{ kind: 'status', name: '反彈', amount: 3, target: 'self' }], upgrade: { effects: [{ kind: 'status', name: '反彈', amount: 4, target: 'self' }] } },
  { id: 'renwuwancheng', name: '任務完成', cost: 1, type: 能, rarity: '稀有', pool: '忍術', target: 'self', art: 'ninja/04',
    effects: [{ kind: 'power', trigger: 'onKill', effects: [{ kind: 'heal', n: 6 }] }],
    upgrade: { effects: [{ kind: 'power', trigger: 'onKill', effects: [{ kind: 'heal', n: 8 }] }] } },
  { id: 'fengyin', name: '封印解除', cost: 3, type: 能, rarity: '稀有', pool: '忍術', target: 'self', art: 'ninja/18',
    effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'status', name: '爪力', amount: 1, target: 'self' }] }], upgrade: { cost: 2 } },

  // ===== 絕學（18） =====
  { id: 'tieshazhang', name: '絕學·鐵砂掌', cost: 1, type: 攻, rarity: '常見', pool: '絕學', target: 'enemy', art: 'daxia/08',
    effects: [{ kind: 'damage', amount: 6 }, { kind: 'status', name: '噎到', amount: 3, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 8 }, { kind: 'status', name: '噎到', amount: 4, target: 'enemy' }] } },
  { id: 'qinna', name: '絕學·擒拿手', cost: 1, type: 攻, rarity: '常見', pool: '絕學', target: 'enemy', art: 'daxia/09',
    effects: [{ kind: 'damage', amount: 7 }, { kind: 'status', name: '炸毛', amount: 2, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 9 }, { kind: 'status', name: '炸毛', amount: 3, target: 'enemy' }] } },
  { id: 'juye', name: '絕學·聚葉成刀', cost: 1, type: 攻, rarity: '常見', pool: '絕學', target: 'enemy', art: 'daxia/14',
    effects: [{ kind: 'damage', amount: 3, times: 3 }], upgrade: { effects: [{ kind: 'damage', amount: 4, times: 3 }] } },
  { id: 'jinzhong', name: '絕學·金鐘罩', cost: 2, type: 技, rarity: '常見', pool: '絕學', target: 'self', art: 'daxia/07',
    effects: [{ kind: 'block', amount: 14 }], upgrade: { effects: [{ kind: 'block', amount: 18 }] } },
  { id: 'qinggong', name: '絕學·輕功', cost: 1, type: 技, rarity: '常見', pool: '絕學', target: 'self', art: 'daxia/11',
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'draw', n: 2 }], upgrade: { cost: 0 } },
  { id: 'taxue', name: '絕學·踏雪無痕', cost: 0, type: 技, rarity: '常見', pool: '絕學', target: 'self', art: 'daxia/12', keywords: ['消耗'],
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }], upgrade: { keywords: [] } },
  { id: 'xuli', name: '絕學·蓄力', cost: 1, type: 技, rarity: '常見', pool: '絕學', target: 'self', art: 'daxia/21',
    effects: [{ kind: 'doubleNextAttack' }], upgrade: { cost: 0 } },
  { id: 'tietou', name: '絕學·鐵頭功', cost: 2, type: 攻, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'daxia/05',
    effects: [{ kind: 'damage', amount: 16 }, { kind: 'selfDamage', amount: 2 }],
    upgrade: { effects: [{ kind: 'damage', amount: 20 }, { kind: 'selfDamage', amount: 2 }] } },
  { id: 'shihou', name: '絕學·獅吼功', cost: 2, type: 攻, rarity: '罕見', pool: '絕學', target: 'all', art: 'daxia/06',
    effects: [{ kind: 'damage', amount: 10, target: 'all' }, { kind: 'status', name: '懶洋洋', amount: 1, target: 'all' }],
    upgrade: { effects: [{ kind: 'damage', amount: 13, target: 'all' }, { kind: 'status', name: '懶洋洋', amount: 1, target: 'all' }] } },
  { id: 'dianxue', name: '絕學·點穴手', cost: 1, type: 攻, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'daxia/10',
    effects: [{ kind: 'damage', amount: 6 }, { kind: 'status', name: '定身', amount: 1, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 9 }, { kind: 'status', name: '定身', amount: 1, target: 'enemy' }] } },
  { id: 'zuiquan', name: '絕學·醉拳', cost: 1, type: 攻, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'daxia/16',
    effects: [{ kind: 'damageRandom', min: 4, max: 14 }], upgrade: { effects: [{ kind: 'damageRandom', min: 8, max: 18 }] } },
  { id: 'yixing', name: '絕學·移形換影', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'self', art: 'daxia/13',
    effects: [{ kind: 'draw', n: 3 }, { kind: 'discardFromHand', n: 1 }], upgrade: { effects: [{ kind: 'draw', n: 4 }, { kind: 'discardFromHand', n: 1 }] } },
  { id: 'gekong', name: '絕學·隔空取物', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'self', art: 'daxia/15',
    effects: [{ kind: 'recoverFromDiscard' }], upgrade: { cost: 0 } },
  { id: 'guixi', name: '絕學·龜息術', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'self', art: 'daxia/17', keywords: ['消耗'],
    effects: [{ kind: 'heal', n: 8 }], upgrade: { effects: [{ kind: 'heal', n: 12 }] } },
  { id: 'taiji', name: '絕學·太極', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'daxia/18',
    effects: [{ kind: 'damageEqualBlock' }], upgrade: { cost: 0 } },
  { id: 'mabu', name: '絕學·馬步', cost: 1, type: 能, rarity: '罕見', pool: '絕學', target: 'self', art: 'daxia/19',
    effects: [{ kind: 'status', name: '貓步', amount: 2, target: 'self' }], upgrade: { effects: [{ kind: 'status', name: '貓步', amount: 3, target: 'self' }] } },
  { id: 'yungong', name: '絕學·運功', cost: 1, type: 能, rarity: '罕見', pool: '絕學', target: 'self', art: 'daxia/20',
    effects: [{ kind: 'status', name: '爪力', amount: 2, target: 'self' }], upgrade: { effects: [{ kind: 'status', name: '爪力', amount: 3, target: 'self' }] } },
  { id: 'yide', name: '絕學·以德服人', cost: 2, type: 技, rarity: '稀有', pool: '絕學', target: 'all', art: 'daxia/22',
    effects: [{ kind: 'status', name: '懶洋洋', amount: 3, target: 'all' }, { kind: 'heal', n: 5 }], upgrade: { cost: 1 } },

  // ===== 壞毛病（4） =====
  { id: 'zhongji', name: '中計了', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'ninja/34', keywords: ['不可打出'], effects: [], upgrade: {} },
  { id: 'shishou', name: '失手了', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'ninja/35', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onTurnEnd: 1 } },
  { id: 'zouhuo', name: '走火入魔', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'daxia/33', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onTurnStart: 2 } },
  { id: 'neili', name: '內力不足', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'daxia/34', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onDraw: 'loseEnergy' } },
];

export const cardById: Record<string, CardDef> = Object.fromEntries(cards.map((c) => [c.id, c]));

export const STARTER_DECK: string[] = [
  'sanjo', 'sanjo', 'sanjo', 'sanjo', 'sanjo',
  'tanding', 'tanding', 'tanding', 'tanding', 'kawarimi',
];
