import type { CardDef } from '../engine/types';

const 攻 = '攻擊', 技 = '技能', 能 = '能力';

export const cards: readonly CardDef[] = [
  // ===== 起手 =====
// 2026-09-01 平衡：常見牌（0 費與起手牌除外）傷害與蜷縮各 +1——實測每場勝仗平均掉 15~25 血，
// 消耗跟不上回復（貓窩一次只回 21），病根之一是基本牌的交換效率太差。使用者拍板加強。
  { id: 'sanjo', name: '貓抓', cost: 1, type: 攻, rarity: '常見', pool: '起手', target: 'enemy', art: 'card/sanjo',
    effects: [{ kind: 'damage', amount: 6 }], upgrade: { effects: [{ kind: 'damage', amount: 9 }] } },
  { id: 'tanding', name: '淡定', cost: 1, type: 技, rarity: '常見', pool: '起手', target: 'self', art: 'card/tanding',
    effects: [{ kind: 'block', amount: 5 }], upgrade: { effects: [{ kind: 'block', amount: 8 }] } },
  { id: 'kawarimi', name: '忍術·替身術', cost: 2, type: 技, rarity: '常見', pool: '起手', target: 'self', art: 'card/kawarimi',
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'draw', n: 1 }] } },

  // ===== 忍術（33） =====
  { id: 'shunkan', name: '忍術·瞬間移動', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/shunkan',
    effects: [{ kind: 'damage', amount: 8, ignoreBlock: true }], upgrade: { effects: [{ kind: 'damage', amount: 11, ignoreBlock: true }] } },
  { id: 'shengdong', name: '忍術·聲東擊西', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/shengdong',
    effects: [{ kind: 'damage', amount: 6 }, { kind: 'status', name: '懶洋洋', amount: 1, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 8 }, { kind: 'status', name: '懶洋洋', amount: 2, target: 'enemy' }] } },
  { id: 'shunshou', name: '忍術·順手牽羊', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/shunshou',
    effects: [{ kind: 'damage', amount: 7 }, { kind: 'gold', n: 15, onKill: true }],
    upgrade: { effects: [{ kind: 'damage', amount: 10 }, { kind: 'gold', n: 25, onKill: true }] } },
  { id: 'wozaizhe', name: '我在這', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/wozaizhe',
    effects: [{ kind: 'damage', amount: 7 }, { kind: 'drawIfTargetStatus', name: '翻肚', n: 1 }],
    upgrade: { effects: [{ kind: 'damage', amount: 10 }, { kind: 'drawIfTargetStatus', name: '翻肚', n: 1 }] } },
  { id: 'jiaochulai', name: '交出來', cost: 2, type: 技, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/jiaochulai',
    effects: [{ kind: 'stealBlock' }, { kind: 'damage', amount: 5 }], upgrade: { effects: [{ kind: 'stealBlock' }, { kind: 'damage', amount: 7 }] } },
  { id: 'susu', name: '速速退散', cost: 2, type: 攻, rarity: '常見', pool: '忍術', target: 'all', art: 'card/susu',
    effects: [{ kind: 'damage', amount: 9, target: 'all' }], upgrade: { effects: [{ kind: 'damage', amount: 12, target: 'all' }] } },
  { id: 'bunshin', name: '忍術·分身術', cost: 1, type: 攻, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/bunshin',
    effects: [{ kind: 'damage', amount: 3, scaleWithCombo: true, comboCap: 5 }],
    upgrade: { effects: [{ kind: 'damage', amount: 4, scaleWithCombo: true, comboCap: 5 }] } },
  { id: 'ruying', name: '如影隨形', cost: 2, type: 攻, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/ruying',
    effects: [{ kind: 'damage', amount: 5, times: 2 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'damage', amount: 7, times: 2 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }] } },
  { id: 'zhangyan', name: '忍術·障眼法', cost: 2, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/zhangyan',
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'draw', n: 1 }],
    upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'draw', n: 2 }] } },
  { id: 'yinshen', name: '忍術·隱身術', cost: 3, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/yinshen',
    effects: [{ kind: 'status', name: '隱身', amount: 2, target: 'self' }], upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 3, target: 'self' }] } },
  { id: 'bianshen', name: '忍術·變身術', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/bianshen',
    effects: [{ kind: 'block', amount: 10 }], upgrade: { effects: [{ kind: 'block', amount: 13 }] } },
  { id: 'zhuangsi', name: '忍術·裝死術', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/zhuangsi', keywords: ['消耗'],
    effects: [{ kind: 'block', amount: 6 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'block', amount: 9 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }] } },
  { id: 'duxin', name: '忍術·讀心術', cost: 2, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/duxin',
    effects: [{ kind: 'scry', n: 3 }, { kind: 'draw', n: 1 }], upgrade: { effects: [{ kind: 'scry', n: 5 }, { kind: 'draw', n: 1 }] } },
  { id: 'qianliyan', name: '千里眼', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/qianliyan',
    effects: [{ kind: 'draw', n: 2 }], upgrade: { effects: [{ kind: 'draw', n: 3 }] } },
  { id: 'shunfenger', name: '順風耳', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/shunfenger',
    effects: [{ kind: 'drawNextTurn', n: 2 }], upgrade: { effects: [{ kind: 'drawNextTurn', n: 3 }] } },
  { id: 'dingshang', name: '盯上你了', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/dingshang',
    effects: [{ kind: 'status', name: '翻肚', amount: 2, target: 'enemy' }], upgrade: { effects: [{ kind: 'status', name: '翻肚', amount: 3, target: 'enemy' }] } },
  { id: 'chudashi', name: '出大事了', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/chudashi',
    // 比千里眼（1 費抽 2 無代價）多個缺點零補償；抽 3＝高風險高報酬，升級版拿掉代價
    effects: [{ kind: 'draw', n: 3 }, { kind: 'status', name: '翻肚', amount: 1, target: 'self' }], upgrade: { effects: [{ kind: 'draw', n: 3 }] } },
  { id: 'youcike', name: '有刺客', cost: 0, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/youcike', keywords: ['消耗'],
    effects: [{ kind: 'draw', n: 2 }], upgrade: { effects: [{ kind: 'draw', n: 3 }] } },
  { id: 'zhanshu', name: '戰術撤退', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/zhanshu',
    // 比變身術（1 費 10 蜷縮無限制）多個缺點還少 1 點＝純劣化；補一張抽牌當「過渡回合」的定位
    effects: [{ kind: 'block', amount: 9 }, { kind: 'draw', n: 1 }, { kind: 'noAttacksThisTurn' }], upgrade: { effects: [{ kind: 'block', amount: 12 }, { kind: 'draw', n: 1 }, { kind: 'noAttacksThisTurn' }] } },
  { id: 'tuozi', name: '忍術·拖字訣', cost: 2, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/tuozi',
    effects: [{ kind: 'retainFromHand', n: 1 }, { kind: 'draw', n: 1 }], upgrade: { effects: [{ kind: 'retainFromHand', n: 2 }, { kind: 'draw', n: 1 }] } },
  { id: 'shuaiguo', name: '忍術·甩鍋術', cost: 2, type: 技, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/shuaiguo',
    effects: [{ kind: 'transferDebuffs' }], upgrade: { cost: 0 } },
  { id: 'dingshen', name: '忍術·定身術', cost: 2, type: 技, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/dingshen',
    effects: [{ kind: 'status', name: '定身', amount: 1, target: 'enemy' }], upgrade: { cost: 0 } },
  { id: 'cuimian', name: '忍術·催眠術', cost: 2, type: 技, rarity: '罕見', pool: '忍術', target: 'all', art: 'card/cuimian',
    effects: [{ kind: 'status', name: '懶洋洋', amount: 2, target: 'all' }, { kind: 'status', name: '炸毛', amount: 2, target: 'all' }],
    upgrade: { effects: [{ kind: 'status', name: '懶洋洋', amount: 3, target: 'all' }, { kind: 'status', name: '炸毛', amount: 3, target: 'all' }] } },
  { id: 'fengkou', name: '忍術·封口術', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/fengkou',
    // 本來整個拆光（爪力、貓步、防禦全歸零）——對疊了 20 點防禦的師父等於一費清場，使用者 2026-09-02：太強。改最多各 5 點
    effects: [{ kind: 'removeStatuses', names: ['爪力', '貓步'], removeBlock: true, max: 5 }],
    upgrade: { effects: [{ kind: 'removeStatuses', names: ['爪力', '貓步'], removeBlock: true, max: 5 }, { kind: 'status', name: '翻肚', amount: 1, target: 'enemy' }] } },
  // 3 費跟隱身術（常見、當下 2 層）幾乎同價還更慢；降 1 費，走「便宜但分期」
  { id: 'qianshui', name: '忍術·潛水術', cost: 2, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'card/qianshui',
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'status', name: '潛水', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 2, target: 'self' }, { kind: 'status', name: '潛水', amount: 2, target: 'self' }] } },
  { id: 'touchi', name: '忍術·偷吃術', cost: 0, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'card/touchi', keywords: ['消耗'],
    effects: [{ kind: 'energy', n: 1 }], upgrade: { effects: [{ kind: 'energy', n: 1 }, { kind: 'draw', n: 1 }] } },
  { id: 'xianshuile', name: '先睡了', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'card/xianshuile',
    effects: [{ kind: 'heal', n: 4 }, { kind: 'endTurn' }], upgrade: { effects: [{ kind: 'heal', n: 7 }, { kind: 'endTurn' }] } },
  { id: 'gaotui', name: '告退', cost: 0, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'card/gaotui', keywords: ['消耗'],
    effects: [{ kind: 'exhaustFromHand', n: 1 }, { kind: 'draw', n: 1 }], upgrade: { effects: [{ kind: 'exhaustFromHand', n: 1 }, { kind: 'draw', n: 2 }] } },
  { id: 'meikandao', name: '我什麼都沒看到', cost: 3, type: 技, rarity: '稀有', pool: '忍術', target: 'self', art: 'card/meikandao', keywords: ['消耗'],
    effects: [{ kind: 'immuneThisTurn' }], upgrade: { cost: 1 } },
  { id: 'jiejie', name: '結界', cost: 2, type: 能, rarity: '罕見', pool: '忍術', target: 'self', art: 'card/jiejie',
    effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'block', amount: 3 }] }],
    upgrade: { effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'block', amount: 4 }] }] } },
  // 跟忍術·反彈只差 1 點＝純劣化，改走攻守一體；純反彈留給忍術·反彈
  { id: 'fantan', name: '反彈', cost: 1, type: 能, rarity: '罕見', pool: '忍術', target: 'self', art: 'card/fantan',
    effects: [{ kind: 'status', name: '反彈', amount: 2, target: 'self' }, { kind: 'block', amount: 6 }],
    upgrade: { effects: [{ kind: 'status', name: '反彈', amount: 3, target: 'self' }, { kind: 'block', amount: 8 }] } },
  // 基礎版只有本回合有效（`thisTurn`），磨爪之後變成永久的——升級同時拿掉限制又加量
  { id: 'renwuwancheng', name: '忍術·吸貓大法', cost: 1, type: 能, rarity: '稀有', pool: '忍術', target: 'self', art: 'card/renwuwancheng',
    effects: [{ kind: 'power', trigger: 'onKill', thisTurn: true, effects: [{ kind: 'heal', n: 4 }] }],
    upgrade: { effects: [{ kind: 'power', trigger: 'onKill', effects: [{ kind: 'heal', n: 6 }] }] } },
  { id: 'fengyin', name: '封印解除', cost: 3, type: 能, rarity: '稀有', pool: '忍術', target: 'self', art: 'card/fengyin',
    // 原本跟鐵心（2 費）同效果還貴 1 費＝純劣化，改成攻防雙成長，3 費才值
    // 機器人 300 局：到第三關的牌組 65% 有這張，是爪力堆最快的單一來源（每回合 +1 爪力 +1 貓步，打完最終戰 +14）。
    // 升級本來降到 2 費＝更早開起來；改成費用不變、打出時先各得 2 點（使用者 2026-09-02：爪力堆太快）
    effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'status', name: '爪力', amount: 1, target: 'self' }, { kind: 'status', name: '貓步', amount: 1, target: 'self' }] }],
    upgrade: { effects: [{ kind: 'status', name: '爪力', amount: 2, target: 'self' }, { kind: 'status', name: '貓步', amount: 2, target: 'self' }, { kind: 'power', trigger: 'turnStart', effects: [{ kind: 'status', name: '爪力', amount: 1, target: 'self' }, { kind: 'status', name: '貓步', amount: 1, target: 'self' }] }] } },

  // ===== 絕學（18） =====
  { id: 'tieshazhang', name: '絕學·鐵砂掌', cost: 2, type: 攻, rarity: '常見', pool: '絕學', target: 'enemy', art: 'card/tieshazhang',
    effects: [{ kind: 'damage', amount: 7 }, { kind: 'status', name: '噎到', amount: 3, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 9 }, { kind: 'status', name: '噎到', amount: 4, target: 'enemy' }] } },
  { id: 'qinna', name: '絕學·擒拿手', cost: 2, type: 攻, rarity: '常見', pool: '絕學', target: 'enemy', art: 'card/qinna',
    effects: [{ kind: 'damage', amount: 8 }, { kind: 'status', name: '炸毛', amount: 2, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 10 }, { kind: 'status', name: '炸毛', amount: 3, target: 'enemy' }] } },
  // 原本 1 費 4×3 把肉球連擊（1 費 4×2）整張壓死；改打全體、跟十二連環成系列，單體連打讓給肉球
  { id: 'juye', name: '絕學·聚葉成刀', cost: 1, type: 攻, rarity: '常見', pool: '絕學', target: 'all', art: 'card/juye',
    effects: [{ kind: 'damage', amount: 3, times: 2, target: 'all' }], upgrade: { effects: [{ kind: 'damage', amount: 4, times: 2, target: 'all' }] } },
  { id: 'jinzhong', name: '絕學·金鐘罩', cost: 2, type: 技, rarity: '常見', pool: '絕學', target: 'self', art: 'card/jinzhong',
    effects: [{ kind: 'block', amount: 17 }], upgrade: { effects: [{ kind: 'block', amount: 22 }] } },
  // 2026-09-02 使用者：輕功改 2 費、升級 1 費（原本 3 費、升級 0 費）
  { id: 'qinggong', name: '絕學·輕功', cost: 2, type: 技, rarity: '常見', pool: '絕學', target: 'self', art: 'card/qinggong',
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }, { kind: 'draw', n: 2 }], upgrade: { cost: 1 } },
  { id: 'taxue', name: '絕學·踏雪無痕', cost: 0, type: 技, rarity: '稀有', pool: '絕學', target: 'self', art: 'card/taxue', keywords: ['消耗'],
    effects: [{ kind: 'status', name: '隱身', amount: 1, target: 'self' }], upgrade: { keywords: [] } },
  { id: 'xuli', name: '絕學·蓄力', cost: 1, type: 技, rarity: '常見', pool: '絕學', target: 'self', art: 'card/xuli',
    effects: [{ kind: 'doubleNextAttack' }], upgrade: { cost: 0 } },
  { id: 'tietou', name: '絕學·鐵頭功', cost: 2, type: 攻, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'card/tietou',
    effects: [{ kind: 'damage', amount: 16 }, { kind: 'selfDamage', amount: 2 }],
    upgrade: { effects: [{ kind: 'damage', amount: 20 }, { kind: 'selfDamage', amount: 2 }] } },
  { id: 'shihou', name: '絕學·獅吼功', cost: 2, type: 攻, rarity: '罕見', pool: '絕學', target: 'all', art: 'card/shihou',
    effects: [{ kind: 'damage', amount: 10, target: 'all' }, { kind: 'status', name: '懶洋洋', amount: 1, target: 'all' }],
    upgrade: { effects: [{ kind: 'damage', amount: 13, target: 'all' }, { kind: 'status', name: '懶洋洋', amount: 1, target: 'all' }] } },
  { id: 'dianxue', name: '絕學·點穴手', cost: 2, type: 攻, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'card/dianxue',
    effects: [{ kind: 'damage', amount: 6 }, { kind: 'status', name: '定身', amount: 1, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 9 }, { kind: 'status', name: '定身', amount: 1, target: 'enemy' }] } },
  { id: 'zuiquan', name: '絕學·醉拳', cost: 1, type: 攻, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'card/zuiquan',
    effects: [{ kind: 'damageRandom', min: 4, max: 14 }], upgrade: { effects: [{ kind: 'damageRandom', min: 8, max: 18 }] } },
  { id: 'yixing', name: '絕學·移形換影', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'self', art: 'card/yixing',
    effects: [{ kind: 'draw', n: 3 }, { kind: 'discardFromHand', n: 1 }], upgrade: { effects: [{ kind: 'draw', n: 4 }, { kind: 'discardFromHand', n: 1 }] } },
  { id: 'gekong', name: '絕學·隔空取物', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'self', art: 'card/gekong',
    effects: [{ kind: 'recoverFromDiscard' }], upgrade: { cost: 0 } },
  { id: 'guixi', name: '絕學·龜息術', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'self', art: 'card/guixi', keywords: ['消耗'],
    effects: [{ kind: 'heal', n: 10 }], upgrade: { effects: [{ kind: 'heal', n: 14 }] } },
  { id: 'taiji', name: '絕學·太極', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'card/taiji',
    effects: [{ kind: 'damageEqualBlock' }], upgrade: { cost: 0 } },
  { id: 'mabu', name: '絕學·馬步', cost: 1, type: 能, rarity: '罕見', pool: '絕學', target: 'self', art: 'card/mabu',
    effects: [{ kind: 'status', name: '貓步', amount: 2, target: 'self' }], upgrade: { effects: [{ kind: 'status', name: '貓步', amount: 3, target: 'self' }] } },
  { id: 'yungong', name: '絕學·運功', cost: 1, type: 能, rarity: '罕見', pool: '絕學', target: 'self', art: 'card/yungong',
    effects: [{ kind: 'status', name: '爪力', amount: 2, target: 'self' }], upgrade: { effects: [{ kind: 'status', name: '爪力', amount: 3, target: 'self' }] } },
  { id: 'yide', name: '絕學·以德服人', cost: 2, type: 技, rarity: '稀有', pool: '絕學', target: 'all', art: 'card/yide',
    effects: [{ kind: 'status', name: '懶洋洋', amount: 3, target: 'all' }, { kind: 'heal', n: 5 }], upgrade: { cost: 1 } },

  // ===== 壞毛病（4） =====
  { id: 'zhongji', name: '中計了', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'card/zhongji', keywords: ['不可打出'], effects: [], upgrade: {} },
  { id: 'shishou', name: '失手了', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'card/shishou', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onTurnEnd: 1 } },
  { id: 'zouhuo', name: '走火入魔', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'card/zouhuo', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onTurnStart: 2 } },
  { id: 'neili', name: '內力不足', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'card/neili', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onDraw: 'loseEnergy' } },

  // ===== 2026-08-30 新增 20 張 =====
  // 補的是「機制上的空缺」，不是再多幾張打人牌：噎到、反彈、飯糰、隱身收尾原本各只有一兩張撐著，
  // 牌組很難圍繞它們成形。稀有牌也從 4 張補到 7 張——那是每一局最期待的東西。
  { id: 'roubao', name: '肉球連擊', cost: 1, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/roubao',
    effects: [{ kind: 'damage', amount: 4, times: 2 }], upgrade: { effects: [{ kind: 'damage', amount: 5, times: 2 }] } },
  { id: 'luoye', name: '忍術·落葉', cost: 1, type: 攻, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/luoye',
    effects: [{ kind: 'damage', amount: 4 }, { kind: 'draw', n: 1 }],
    upgrade: { effects: [{ kind: 'damage', amount: 6 }, { kind: 'draw', n: 1 }] } },
  { id: 'liangzhua', name: '亮出爪子', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/liangzhua',
    // 升級本來是拿掉「消耗」——一費一次 +1、每輪都能再打，是後期爪力堆最快的來源之一
    // （使用者 2026-09-02：「爪力累積好像太快了」）。改成 +2 但照樣消耗：一局只吃得到一次
    keywords: ['消耗'], effects: [{ kind: 'status', name: '爪力', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'status', name: '爪力', amount: 2, target: 'self' }] } },
  { id: 'suoyituan', name: '縮成一團', cost: 1, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/suoyituan',
    effects: [{ kind: 'block', amount: 5 }, { kind: 'draw', n: 1 }],
    upgrade: { effects: [{ kind: 'block', amount: 7 }, { kind: 'draw', n: 1 }] } },
  // 2026-09-01 使用者點名翻肚（易傷）供給太少（全牌庫只有盯上你了會掛）：威嚇加掛 1 層，
  // 跟盯上你了分工——盯上=純堆層數，威嚇=削攻擊順手掛一層
  // 2026-09-02 使用者：威嚇與威嚇＋太強，改 2 費（原 1 費）
  { id: 'weihe', name: '威嚇', cost: 2, type: 技, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/weihe',
    effects: [{ kind: 'status', name: '炸毛', amount: 2, target: 'enemy' }, { kind: 'status', name: '翻肚', amount: 1, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'status', name: '炸毛', amount: 3, target: 'enemy' }, { kind: 'status', name: '翻肚', amount: 2, target: 'enemy' }] } },
  { id: 'paozhao', name: '忍術·拋爪', cost: 0, type: 攻, rarity: '常見', pool: '忍術', target: 'enemy', art: 'card/paozhao',
    effects: [{ kind: 'damage', amount: 2 }], upgrade: { effects: [{ kind: 'damage', amount: 4 }] } },
  // 0 費回 6（2026-09-01 使用者拍板）：反正是消耗牌、一局只有一次，1 費的門檻只是煩人
  { id: 'tianmao', name: '舔毛', cost: 0, type: 技, rarity: '常見', pool: '忍術', target: 'self', art: 'card/tianmao',
    keywords: ['消耗'], effects: [{ kind: 'heal', n: 6 }], upgrade: { effects: [{ kind: 'heal', n: 9 }] } },
  { id: 'canying', name: '忍術·殘影', cost: 3, type: 攻, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/canying',
    effects: [{ kind: 'damage', amount: 5 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }],
    upgrade: { effects: [{ kind: 'damage', amount: 7 }, { kind: 'status', name: '隱身', amount: 1, target: 'self' }] } },
  { id: 'caiweiba', name: '忍術·踩尾巴', cost: 2, type: 攻, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/caiweiba',
    effects: [{ kind: 'damage', amount: 6 }, { kind: 'status', name: '噎到', amount: 2, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'damage', amount: 6 }, { kind: 'status', name: '噎到', amount: 3, target: 'enemy' }] } },
  { id: 'diaohu', name: '忍術·調虎離山', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'all', art: 'card/diaohu',
    effects: [{ kind: 'status', name: '懶洋洋', amount: 1, target: 'all' }, { kind: 'draw', n: 1 }],
    upgrade: { effects: [{ kind: 'status', name: '懶洋洋', amount: 2, target: 'all' }, { kind: 'draw', n: 1 }] } },
  { id: 'sashoujian', name: '忍術·撒手鐧', cost: 2, type: 攻, rarity: '罕見', pool: '忍術', target: 'enemy', art: 'card/sashoujian',
    effects: [{ kind: 'damage', amount: 12 }, { kind: 'endTurn' }],
    upgrade: { effects: [{ kind: 'damage', amount: 16 }, { kind: 'endTurn' }] } },
  { id: 'jiuming', name: '忍術·九命怪貓', cost: 2, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'card/jiuming',
    keywords: ['消耗'], effects: [{ kind: 'heal', n: 8 }, { kind: 'block', amount: 4 }],
    upgrade: { effects: [{ kind: 'heal', n: 12 }, { kind: 'block', amount: 6 }] } },
  { id: 'fanzhua', name: '忍術·反彈', cost: 1, type: 技, rarity: '罕見', pool: '忍術', target: 'self', art: 'card/fanzhua',
    effects: [{ kind: 'status', name: '反彈', amount: 4, target: 'self' }],
    upgrade: { effects: [{ kind: 'status', name: '反彈', amount: 6, target: 'self' }] } },
  { id: 'wanhua', name: '忍術·萬花筒', cost: 2, type: 能, rarity: '稀有', pool: '忍術', target: 'self', art: 'card/wanhua',
    effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'draw', n: 1 }] }],
    upgrade: { cost: 1 } },
  { id: 'yingzi', name: '影子分身', cost: 2, type: 能, rarity: '稀有', pool: '忍術', target: 'self', art: 'card/yingzi',
    effects: [{ kind: 'power', trigger: 'onKill', effects: [{ kind: 'draw', n: 1 }, { kind: 'status', name: '爪力', amount: 1, target: 'self' }] }],
    upgrade: { effects: [{ kind: 'power', trigger: 'onKill', effects: [{ kind: 'draw', n: 1 }, { kind: 'status', name: '爪力', amount: 1, target: 'self' }, { kind: 'heal', n: 3 }] }] } },
  { id: 'tuishou', name: '絕學·推手', cost: 1, type: 技, rarity: '罕見', pool: '絕學', target: 'enemy', art: 'card/tuishou',
    effects: [{ kind: 'block', amount: 6 }, { kind: 'status', name: '懶洋洋', amount: 1, target: 'enemy' }],
    upgrade: { effects: [{ kind: 'block', amount: 9 }, { kind: 'status', name: '懶洋洋', amount: 1, target: 'enemy' }] } },
  { id: 'dieda', name: '絕學·貓爪抓', cost: 2, type: 攻, rarity: '常見', pool: '絕學', target: 'enemy', art: 'card/dieda',
    effects: [{ kind: 'damage', amount: 6 }, { kind: 'heal', n: 3 }],
    upgrade: { effects: [{ kind: 'damage', amount: 8 }, { kind: 'heal', n: 5 }] } },
  { id: 'shibadie', name: '絕學·沾衣十八跌', cost: 2, type: 攻, rarity: '常見', pool: '絕學', target: 'enemy', art: 'card/shibadie',
    effects: [{ kind: 'damage', amount: 5, times: 3 }], upgrade: { effects: [{ kind: 'damage', amount: 6, times: 3 }] } },
  { id: 'hujin', name: '絕學·護金', cost: 2, type: 技, rarity: '罕見', pool: '絕學', target: 'self', art: 'card/hujin',
    effects: [{ kind: 'block', amount: 10 }, { kind: 'status', name: '反彈', amount: 2, target: 'self' }],
    upgrade: { effects: [{ kind: 'block', amount: 14 }, { kind: 'status', name: '反彈', amount: 3, target: 'self' }] } },
  { id: 'boming', name: '絕學·拼命', cost: 1, type: 技, rarity: '稀有', pool: '絕學', target: 'self', art: 'card/boming',
    keywords: ['消耗'], effects: [{ kind: 'selfDamage', amount: 3 }, { kind: 'energy', n: 2 }],
    upgrade: { effects: [{ kind: 'energy', n: 2 }] } },
  // 2026-08-31 補 4 張壞毛病：本來只有 4 張，事件塞給你的永遠是那幾張
  { id: 'shibai', name: '睡過頭', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'card/shibai', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onTurnStart: 1 } },
  { id: 'maoqiu', name: '吐毛球', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'card/maoqiu', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onTurnEnd: 2 } },
  { id: 'zuiyang', name: '嘴饞', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'card/zuiyang', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onDraw: 'loseEnergy' } },
  { id: 'fanwei', name: '犯胃痛', cost: 0, type: 技, rarity: '常見', pool: '壞毛病', target: 'none', art: 'card/fanwei', keywords: ['不可打出'], effects: [], upgrade: {}, curse: { onTurnEnd: 3 } },
  // 2026-08-31 補 12 張稀有：本來只有 8 張，獎勵畫面很快就重複。
  // 稀有牌該是「改變打法」的，不是「數字比較大」的，所以都掛在少見的機制上。
  // 跟沾衣十八跌一字不差（同 5×3），改走「破防連斬」：打高防怪的稀有解，跟瞬間移動成系列
  { id: 'liandao', name: '絕學·連刀', cost: 2, type: 攻, rarity: '稀有', pool: '絕學', target: 'enemy', art: 'card/liandao',
    effects: [{ kind: 'damage', amount: 4, times: 3, ignoreBlock: true }],
    upgrade: { effects: [{ kind: 'damage', amount: 5, times: 3, ignoreBlock: true }] } },
  { id: 'huanying', name: '忍術·幻影分身', cost: 2, type: 技, rarity: '稀有', pool: '忍術', target: 'self', art: 'card/huanying',
    effects: [{ kind: 'status', name: '隱身', amount: 3, target: 'self' }, { kind: 'draw', n: 2 }],
    upgrade: { effects: [{ kind: 'status', name: '隱身', amount: 4, target: 'self' }, { kind: 'draw', n: 3 }] } },
  { id: 'jiedao', name: '絕學·借刀', cost: 1, type: 攻, rarity: '稀有', pool: '絕學', target: 'enemy', art: 'card/jiedao',
    effects: [{ kind: 'damageEqualBlock' }, { kind: 'block', amount: 6 }],
    upgrade: { effects: [{ kind: 'damageEqualBlock' }, { kind: 'block', amount: 10 }] } },
  { id: 'wangming', name: '絕學·亡命', cost: 0, type: 攻, rarity: '稀有', pool: '絕學', target: 'enemy', art: 'card/wangming', keywords: ['消耗'],
    effects: [{ kind: 'damage', amount: 20 }, { kind: 'selfDamage', amount: 6 }],
    upgrade: { effects: [{ kind: 'damage', amount: 26 }, { kind: 'selfDamage', amount: 6 }] } },
  { id: 'wufeng', name: '忍術·無風', cost: 1, type: 能, rarity: '稀有', pool: '忍術', target: 'self', art: 'card/wufeng',
    effects: [{ kind: 'power', trigger: 'turnEndNoAttack', effects: [{ kind: 'block', amount: 8 }] }],
    upgrade: { effects: [{ kind: 'power', trigger: 'turnEndNoAttack', effects: [{ kind: 'block', amount: 12 }] }] } },
  { id: 'tiexin', name: '絕學·鐵心', cost: 2, type: 能, rarity: '稀有', pool: '絕學', target: 'self', art: 'card/tiexin',
    effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'status', name: '爪力', amount: 1, target: 'self' }] }],
    // 升級本來是 2 費→1 費：成長引擎變成順手一丟，後期滾太快（使用者 2026-09-02）。改成打出時先得 2 點、費用不變
    upgrade: { effects: [{ kind: 'status', name: '爪力', amount: 2, target: 'self' }, { kind: 'power', trigger: 'turnStart', effects: [{ kind: 'status', name: '爪力', amount: 1, target: 'self' }] }] } },
  // 費 2 回 2＝淨零，牌面讀起來像白忙一場，而且飽足剩 1 點時打不出來——
  // 偏偏那正是最需要補牌的時候。改成費 1 回 2：真的聚到氣，名字才名副其實。
  { id: 'sanhua', name: '忍術·三花聚頂', cost: 1, type: 技, rarity: '稀有', pool: '忍術', target: 'self', art: 'card/sanhua',
    effects: [{ kind: 'draw', n: 3 }, { kind: 'energy', n: 2 }],
    upgrade: { effects: [{ kind: 'draw', n: 4 }, { kind: 'energy', n: 2 }] } },
  { id: 'fanpu', name: '絕學·返璞', cost: 1, type: 技, rarity: '稀有', pool: '絕學', target: 'self', art: 'card/fanpu', keywords: ['消耗'],
    effects: [{ kind: 'cleanse' }, { kind: 'heal', n: 8 }],
    upgrade: { effects: [{ kind: 'cleanse' }, { kind: 'heal', n: 14 }] } },
  { id: 'shierlian', name: '絕學·十二連環', cost: 3, type: 攻, rarity: '稀有', pool: '絕學', target: 'all', art: 'card/shierlian',
    effects: [{ kind: 'damage', amount: 6, target: 'all', times: 2 }],
    upgrade: { effects: [{ kind: 'damage', amount: 8, target: 'all', times: 2 }] } },
  { id: 'jingzhi', name: '忍術·靜止', cost: 2, type: 技, rarity: '稀有', pool: '忍術', target: 'all', art: 'card/jingzhi',
    effects: [{ kind: 'status', name: '定身', amount: 1, target: 'all' }],
    upgrade: { cost: 1 } },
  { id: 'huxin', name: '絕學·護心', cost: 1, type: 能, rarity: '稀有', pool: '絕學', target: 'self', art: 'card/huxin',
    effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'block', amount: 5 }] }],
    upgrade: { effects: [{ kind: 'power', trigger: 'turnStart', effects: [{ kind: 'block', amount: 8 }] }] } },
  // 2 費打 9 再 +2 爪力、不消耗＝每兩回合就 +2，是稀有牌裡滾最快的。使用者 2026-09-02：「讓某些強力牌 COST 較高」
  // → 抬到 3 費（一回合的飽足全押在這張上），傷害補到 11／15 讓它仍然值得打
  { id: 'jiuweiquan', name: '絕學·九尾拳', cost: 3, type: 攻, rarity: '稀有', pool: '絕學', target: 'enemy', art: 'card/jiuweiquan',
    effects: [{ kind: 'damage', amount: 11 }, { kind: 'status', name: '爪力', amount: 2, target: 'self' }],
    upgrade: { effects: [{ kind: 'damage', amount: 15 }, { kind: 'status', name: '爪力', amount: 2, target: 'self' }] } },
];

export const cardById: Record<string, CardDef> = Object.fromEntries(cards.map((c) => [c.id, c]));

export const STARTER_DECK: readonly string[] = [
  'sanjo', 'sanjo', 'sanjo', 'sanjo', 'sanjo',
  'tanding', 'tanding', 'tanding', 'tanding', 'kawarimi',
];
