import type { EventDef } from '../engine/types';

/*
 * ===== 內容擴充第二批的事件（2026-09-23，劇本 design2 第三～六節）=====
 *
 * 十八篇：兩條三集的事件鏈（迷路的郵差鴿、影子的真面目）、三關各三篇的關卡限定、連線限定三篇。
 * 文字照劇本照抄，**四隻的開頭與結果全部在 `event-text-b2.ts`**（延後載入，事件畫面才抓）：這裡的 `text`、`result`
 * 故意留空，那支一載入就把球球那份填回來（2026-09-23 b2fin，主控裁定跟另外三隻一樣延後載入；
 * 原本球球那份寫在這裡，首載程式多揹二十幾 KB）。**只有事件畫面與除錯總覽讀得到文字**，首載的模組別來讀。
 * 選項標籤與標題留在這裡（標籤寫著效果，跟 `outcome` 一起看才對得上）。
 * 效果照劇本表格轉；選項順序跟插圖的結果序號綁在一起（`_r0`／`_r1`／`_r2`，
 * 美術代理 art3、art4 的對照表），也跟 `NINJA_EVENT_TEXT_B2` 的 `results` 一一對應，不要調換。
 *
 * - 鏈的旗標一律 `chain:` 開頭（收進整局指紋）；後一集用 `requiresFlag` 接前一集，走現成的「後集優先」，
 *   一關一集（第一集 `acts:[1]`、第二集 `[2]`、第三集 `[3]`）。
 * - 影子鏈只在單人排（`soloOnly`：鏡中對手在連線時照座位 0 變裝，坐 1 號的人會打到同伴的影子）；
 *   單人球球的第二集換成他自己的「屋頂上的影子」（`soloHeroSwap`，主控 2026-09-23 裁定照劇本新9）。
 *   影子那一場打的是 `shadow_duel`（同一隻鏡中對手，名牌與開場白換成「某某的影子」，見 `content/enemies.ts`）。
 * - 連線限定三篇（`coopOnly`）：①② 是同一件事、角色對調，`bySeat` 是［座位 0, 座位 1］；
 *   標籤與結果文字照 `EventChoice.bySeat` 的約定寫（`choices[0]`＝「我拿」、`choices[1]`＝「我付」，座位 0 的視角），
 *   「{同伴}」「{稱}」「{對方}」由事件畫面照同伴換掉（`event-text-b2.ts` 的 `coopFill`）。
 * - 條件選項（影子的真面目③、風裡的回信③）加在 `choices` 最後，條件提示句在 `event-text-b2.ts`。
 */
export const batch2Events: EventDef[] = [
  { id: 'pigeon_lost', title: '迷路的郵差鴿', acts: [1], weight: 3,
    text: '',
    choices: [
      { label: '爬上去解開背帶，把信撿齊（最多失去 4 點生命）',
        outcome: [{ kind: 'flag', name: 'chain:pigeon_1' }, { kind: 'damage', n: 4 }],
        result: '', resultArt: 'pigeon_lost_r0' },
      { label: '勾斷背帶讓牠先飛（隨機獲得 1 個忍具）',
        outcome: [{ kind: 'potions', n: 1 }],
        result: '', resultArt: 'pigeon_lost_r1' },
      { label: '不管牠，繼續走（無效果）',
        outcome: [],
        result: '' },
    ] },
  { id: 'pigeon_grandpa', title: '給爺爺的信', acts: [2], requiresFlag: 'chain:pigeon_1',
    text: '',
    choices: [
      { label: '念信給爺爺聽（生命上限與當前生命各 +6）',
        outcome: [{ kind: 'flag', name: 'chain:pigeon_2' }, { kind: 'flag', name: 'chain:pigeon_read' }, { kind: 'maxHp', n: 6 }],
        result: '', resultArt: 'pigeon_grandpa_r0' },
      { label: '替爺爺寫回信，他說你寫（自選升級至多 1 張牌）',
        outcome: [{ kind: 'flag', name: 'chain:pigeon_2' }, { kind: 'flag', name: 'chain:pigeon_wrote' }, { kind: 'upgradeCard' }],
        result: '', resultArt: 'pigeon_grandpa_r1' },
      { label: '把信交到他手上就走（獲得 40 條小魚乾）',
        outcome: [{ kind: 'flag', name: 'chain:pigeon_2' }, { kind: 'fish', n: 40 }],
        result: '', resultArt: 'pigeon_grandpa_r2' },
    ] },
  { id: 'pigeon_reply', title: '風裡的回信', acts: [3], requiresFlag: 'chain:pigeon_2',
    text: '',
    choices: [
      { label: '收下爺爺的謝禮（隨機獲得 1 件塔主秘寶）',
        outcome: [{ kind: 'relic', pool: '塔主' }],
        result: '', resultArt: 'pigeon_reply_r0' },
      { label: '把謝禮託鴿子帶回給爺爺，只留下那張畫（生命回復至上限）',
        outcome: [{ kind: 'healPercent', p: 1 }],
        result: '', resultArt: 'pigeon_reply_r1' },
      { label: '拆開信封裡夾的第二張紙（從 3 張絕學牌中選擇 1 張、回復 12 點生命）', requires: { kind: 'flag', name: 'chain:pigeon_wrote' }, requiresLabel: '回信',
        outcome: [{ kind: 'chooseCard', pool: '絕學', n: 3 }, { kind: 'heal', n: 12 }],
        result: '', resultArt: 'pigeon_reply_r2' },
    ] },
  { id: 'shadow_loose', title: '影子不見了', acts: [1], soloOnly: true, weight: 3,
    text: '',
    choices: [
      { label: '追上去（最多失去 5 點生命；從 3 張忍術牌中選擇 1 張）',
        outcome: [{ kind: 'flag', name: 'chain:shadow_1' }, { kind: 'damage', n: 5 }, { kind: 'chooseCard', pool: '忍術', n: 3 }],
        result: '', resultArt: 'shadow_loose_r0' },
      { label: '拿火把把它照回腳下（自選升級至多 1 張牌）',
        outcome: [{ kind: 'upgradeCard' }],
        result: '', resultArt: 'shadow_loose_r1' },
      { label: '不管它，沒影子也能走（無效果）',
        outcome: [],
        result: '' },
    ] },
  { id: 'shadow_study', title: '偷練的影子', acts: [2], soloOnly: true, requiresFlag: 'chain:shadow_1', soloHeroSwap: { ninja: 'ninja_roof_shadow' },
    text: '',
    choices: [
      { label: '推開門，跟它打一場（勝利後可升級至多 1 張牌，另得 30 條小魚乾）',
        outcome: [{ kind: 'flag', name: 'chain:shadow_2' }, { kind: 'flag', name: 'chain:shadow_2_fought' }, { kind: 'fight', encounterId: 'shadow_duel', bonusFish: 30, bonusUpgrades: 1 }],
        result: '' },
      { label: '躲在門外看它練完（自選升級至多 1 張牌）',
        outcome: [{ kind: 'flag', name: 'chain:shadow_2' }, { kind: 'flag', name: 'chain:shadow_2_watched' }, { kind: 'upgradeCard' }],
        result: '', resultArt: 'shadow_study_r1' },
    ] },
  { id: 'shadow_truth', title: '影子的真面目', acts: [3], soloOnly: true, requiresFlag: 'chain:shadow_2',
    text: '',
    choices: [
      { label: '攔下它，打一場（勝利後可升級至多 2 張牌，另得 40 條小魚乾）',
        outcome: [{ kind: 'fight', encounterId: 'shadow_duel', bonusFish: 40, bonusUpgrades: 2 }],
        result: '' },
      { label: '伸出手，跟它要那把木劍（獲得「師父的舊木劍」；回復 10 點生命）',
        outcome: [{ kind: 'relicId', id: 'master_wooden_sword', fallbackFish: 60 }, { kind: 'heal', n: 10 }],
        result: '', resultArt: 'shadow_truth_r1' },
      { label: '陪它把那一套練完（從 3 張絕學牌中選擇 1 張、自選升級至多 1 張牌）', requires: { kind: 'flag', name: 'chain:shadow_2_watched' }, requiresLabel: '看過它練',
        outcome: [{ kind: 'chooseCard', pool: '絕學', n: 3 }, { kind: 'upgradeCard' }],
        result: '', resultArt: 'shadow_truth_r2' },
    ] },
  { id: 'cell_bandit', title: '牢裡的山賊', acts: [1],
    text: '',
    choices: [
      { label: '撬開鎖放牠出來（最多失去 5 點生命；獲得「山賊的欠條」）',
        outcome: [{ kind: 'damage', n: 5 }, { kind: 'relicId', id: 'bandit_iou', fallbackFish: 60 }],
        result: '', resultArt: 'cell_bandit_r0' },
      { label: '照牆上的地圖挖出老鼠兵的藏貨，不放牠（獲得 50 條小魚乾）',
        outcome: [{ kind: 'fish', n: 50 }],
        result: '', resultArt: 'cell_bandit_r1' },
      { label: '不理牠（無效果）',
        outcome: [],
        result: '' },
    ] },
  { id: 'rat_bathhouse', title: '老鼠開的澡堂', acts: [1],
    text: '',
    choices: [
      { label: '付 20 條，行囊寄在櫃台，好好泡一場（回復相當於生命上限 40% 的生命；可能少掉 1 個忍具）', costFish: 20,
        outcome: [{ kind: 'healPercent', p: 0.4 }, { kind: 'losePotion' }],
        result: '', resultArt: 'rat_bathhouse_r0' },
      { label: '不付錢，抱著行囊蹲在門邊蹭熱氣（回復 8 點生命）',
        outcome: [{ kind: 'heal', n: 8 }],
        result: '', resultArt: 'rat_bathhouse_r1' },
      { label: '假裝去泡，盯住櫃台（進入戰鬥，勝利後額外獲得 45 條小魚乾）',
        outcome: [{ kind: 'fight', encounterId: 'rats3', bonusFish: 45 }],
        result: '' },
    ] },
  { id: 'bear_cellar', title: '地窖裡的冬眠熊', acts: [1],
    text: '',
    choices: [
      { label: '從牠懷裡抽出布包（最多失去 8 點生命；隨機獲得 1 件常見秘寶）',
        outcome: [{ kind: 'damage', n: 8 }, { kind: 'relic', pool: '常見' }],
        result: '', resultArt: 'bear_cellar_r0' },
      { label: '替牠把滑掉的被子蓋好（回復 8 點生命、隨機獲得 1 個忍具）',
        outcome: [{ kind: 'heal', n: 8 }, { kind: 'potions', n: 1 }],
        result: '', resultArt: 'bear_cellar_r1' },
      { label: '搖醒牠，當面討（進入戰鬥；勝利後隨機獲得 1 件常見秘寶，另得 30 條小魚乾）',
        outcome: [{ kind: 'relic', pool: '常見' }, { kind: 'fight', encounterId: 'hibernating_bear', bonusFish: 30 }],
        result: '' },
    ] },
  { id: 'library_ladder', title: '書庫的梯子', acts: [2],
    text: '',
    choices: [
      { label: '推著梯子爬到最高那層（最多失去 5 點生命；從 3 張絕學牌中選擇 1 張）',
        outcome: [{ kind: 'damage', n: 5 }, { kind: 'chooseCard', pool: '絕學', n: 3 }],
        result: '', resultArt: 'library_ladder_r0' },
      { label: '付 40 條押金，借一本坐在地上讀完（自選升級至多 2 張牌；押金不退）', costFish: 40,
        outcome: [{ kind: 'upgradeCard' }, { kind: 'upgradeCard' }],
        result: '', resultArt: 'library_ladder_r1' },
      { label: '在書架中間睡一覺（回復 16 點生命）',
        outcome: [{ kind: 'heal', n: 16 }],
        result: '', resultArt: 'library_ladder_r2' },
    ] },
  { id: 'tower_kitchen', title: '送上樓的便當', acts: [2],
    text: '',
    choices: [
      { label: '當場吃一個（回復 15 點生命）',
        outcome: [{ kind: 'heal', n: 15 }],
        result: '', resultArt: 'tower_kitchen_r0' },
      { label: '包一個帶走（下一場戰鬥開始時獲得 2 點爪力與 8 點蜷縮）',
        outcome: [{ kind: 'nextFight', effects: [{ kind: 'status', name: '爪力', amount: 2, target: 'self' }, { kind: 'block', amount: 8 }], note: '把帶在身上的便當吃了' }],
        result: '', resultArt: 'tower_kitchen_r1' },
      { label: '捲起袖子幫牠們包便當（獲得 45 條小魚乾）',
        outcome: [{ kind: 'fish', n: 45 }],
        result: '', resultArt: 'tower_kitchen_r2' },
    ] },
  { id: 'wooden_men_alley', title: '木人巷', acts: [2],
    text: '',
    choices: [
      { label: '一口氣走過木人巷（最多失去 10 點生命；自選升級至多 2 張牌）',
        outcome: [{ kind: 'damage', n: 10 }, { kind: 'upgradeCard' }, { kind: 'upgradeCard' }],
        result: '', resultArt: 'wooden_men_alley_r0' },
      { label: '鑽到機關底下撿零件（隨機獲得 1 張罕見忍術牌、獲得 25 條小魚乾）',
        outcome: [{ kind: 'addRandomCard', pool: '忍術', rarity: '罕見' }, { kind: 'fish', n: 25 }],
        result: '', resultArt: 'wooden_men_alley_r1' },
      { label: '掀開牆上的木板，關掉總開關（進入戰鬥；勝利後隨機獲得 1 件常見秘寶）',
        outcome: [{ kind: 'relic', pool: '常見' }, { kind: 'fight', encounterId: 'wood_dummy', bonusFish: 0 }],
        result: '' },
    ] },
  { id: 'fallen_star', title: '掉下來的星星', acts: [3],
    text: '',
    choices: [
      { label: '撿起來帶走（最多失去 8 點生命；隨機獲得 1 件大魔物秘寶）',
        outcome: [{ kind: 'damage', n: 8 }, { kind: 'relic', pool: '大魔物' }],
        result: '', resultArt: 'fallen_star_r0' },
      { label: '用水澆涼，刮下一點星屑（自選升級至多 1 張牌、隨機獲得 1 個忍具）',
        outcome: [{ kind: 'upgradeCard' }, { kind: 'potions', n: 1 }],
        result: '', resultArt: 'fallen_star_r1' },
      { label: '把它丟回天上（生命上限與當前生命各 +9）',
        outcome: [{ kind: 'maxHp', n: 9 }],
        result: '', resultArt: 'fallen_star_r2' },
    ] },
  { id: 'wind_chimes', title: '風鈴長廊', acts: [3],
    text: '',
    choices: [
      { label: '閉上眼睛聽完一整套（自選移除 1 張牌、回復 8 點生命）',
        outcome: [{ kind: 'removeCard' }, { kind: 'heal', n: 8 }],
        result: '', resultArt: 'wind_chimes_r0' },
      { label: '在風裡跟著鈴聲練步法（最多失去 6 點生命；自選升級至多 1 張牌、生命上限與當前生命各 +4）',
        outcome: [{ kind: 'damage', n: 6 }, { kind: 'upgradeCard' }, { kind: 'maxHp', n: 4 }],
        result: '', resultArt: 'wind_chimes_r1' },
      { label: '把那個啞掉的風鈴修好帶走（獲得秘寶「風鈴」；已經有的話改拿 60 條小魚乾）',
        outcome: [{ kind: 'relicId', id: 'wind_chime', fallbackFish: 60 }],
        result: '', resultArt: 'wind_chimes_r2' },
    ] },
  { id: 'miasma_crystal', title: '魔氣結晶', acts: [3],
    text: '',
    choices: [
      { label: '把它收進懷裡（獲得「魔氣殘片」）',
        outcome: [{ kind: 'relicId', id: 'miasma_shard', fallbackFish: 60 }],
        result: '', resultArt: 'miasma_crystal_r0' },
      { label: '一擊把它敲碎（最多失去 8 點生命；自選移除 2 張牌）',
        outcome: [{ kind: 'damage', n: 8 }, { kind: 'removeCard' }, { kind: 'removeCard' }],
        result: '', resultArt: 'miasma_crystal_r1' },
      { label: '用布包起來，丟下塔（無效果）',
        outcome: [],
        result: '' },
    ] },
  { id: 'coop_rope_bridge', title: '只撐得住一個人的橋', acts: [1], coopOnly: true,
    text: '',
    choices: [
      { label: '我過橋拿寶箱，{同伴}拉繩（我：隨機獲得 1 件大魔物秘寶；{同伴}：最多失去 10 點生命）', bySeat: [[{ kind: 'relic', pool: '大魔物' }], [{ kind: 'damage', n: 10 }]], outcome: [],
        result: '', resultArt: 'coop_rope_bridge_r0' },
      { label: '{同伴}過橋拿寶箱，我拉繩（{同伴}：隨機獲得 1 件大魔物秘寶；我：最多失去 10 點生命）', bySeat: [[{ kind: 'damage', n: 10 }], [{ kind: 'relic', pool: '大魔物' }]], outcome: [],
        result: '', resultArt: 'coop_rope_bridge_r1' },
      { label: '都不過橋，拆兩塊橋板去賣（兩人各獲得 30 條小魚乾）', outcome: [{ kind: 'fish', n: 30 }],
        result: '', resultArt: 'coop_rope_bridge_r2' },
    ] },
  { id: 'coop_seesaw', title: '翹翹板升降台', acts: [2], coopOnly: true,
    text: '',
    choices: [
      { label: '我坐上去拿架上的東西，{同伴}在下面壓著（我：隨機獲得 1 件常見秘寶與 1 個忍具；{同伴}：自選升級至多 1 張牌、獲得 30 條小魚乾）', bySeat: [[{ kind: 'relic', pool: '常見' }, { kind: 'potions', n: 1 }], [{ kind: 'upgradeCard' }, { kind: 'fish', n: 30 }]], outcome: [],
        result: '', resultArt: 'coop_seesaw_r0' },
      { label: '{同伴}坐上去拿，我在下面壓著（{同伴}：隨機獲得 1 件常見秘寶與 1 個忍具；我：自選升級至多 1 張牌、獲得 30 條小魚乾）', bySeat: [[{ kind: 'upgradeCard' }, { kind: 'fish', n: 30 }], [{ kind: 'relic', pool: '常見' }, { kind: 'potions', n: 1 }]], outcome: [],
        result: '', resultArt: 'coop_seesaw_r1' },
      { label: '兩個人一起玩翹翹板（兩人各回復 12 點生命）', outcome: [{ kind: 'heal', n: 12 }],
        result: '', resultArt: 'coop_seesaw_r2' },
    ] },
  { id: 'coop_shooting_star', title: '只許一個願', acts: [3], coopOnly: true,
    text: '',
    choices: [
      { label: '我許願，{同伴}幫我看著流星（我：隨機獲得 1 件大魔物秘寶；{同伴}：回復 10 點生命）', bySeat: [[{ kind: 'relic', pool: '大魔物' }], [{ kind: 'heal', n: 10 }]], outcome: [],
        result: '', resultArt: 'coop_shooting_star_r0' },
      { label: '讓{同伴}許願，我幫忙看著（{同伴}：隨機獲得 1 件大魔物秘寶；我：回復 10 點生命）', bySeat: [[{ kind: 'heal', n: 10 }], [{ kind: 'relic', pool: '大魔物' }]], outcome: [],
        result: '', resultArt: 'coop_shooting_star_r1' },
      { label: '兩個人一起按，把願望分成兩半（兩人生命上限與當前生命各 +5）', outcome: [{ kind: 'maxHp', n: 5 }],
        result: '', resultArt: 'coop_shooting_star_r2' },
    ] },
];
